### PR TITLE
1.6.0 - Replace request with axios

### PR DESCRIPTION
**Pull request by pkclark**
This PR replaces the long deprecated request module with axios.  It also simplifies client instance fingerprinting, now just using hashed hostname, and deprecates the `getFingerprint` function.

### CODE REVIEW

**Comment by pkclark** [comment]
@lachezar-angelov pulled in retry status check per your comments and @feons's improvement from #31

**Review by lachezar-angelov — APPROVED** [review]
LGTM

**Comment by pkclark** [comment]
Published appc-pubsub@1.6.0. ⚡

**Comment by ashwinkrishna7** [comment]
would be great if you can add https://www.npmjs.com/package/axios new version of axios (0.22.0) and release a new version. Thanks.

**Comment by pkclark** [comment]
@ashutosh49  handled in v1.6.2. See #38

**Pull request merged**
